version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_2fa
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
